[site]
title = "Xinxun Zhang"
description = "PhD student at Wuhan University."
favicon = "/favicon.svg"
last_updated = "March, 2026"

[author]
name = "Xinxun Zhang"
title = "PhD Student"
institution = "Wuhan University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "xxzhangstu@whu.edu.cn"
location = "Wuhan, China"
google_scholar = "https://scholar.google.com/citations?user=VrX_9NkAAAAJ&hl"
github = "https://github.com/xxzhang99/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
