[[internships]]
company = "Tencent"
role = "Reserach Intern"
date = "2025.11 - 2026.02"
project = "Generative Recommendation for Ad"

[[internships]]
company = "Tencent"
role = "Reserach Intern"
date = "2026.03 - Now"
project = "Generative Recommendation Infra"
