[[news]]
date = "2025-11"
content = "One paper accepted by AAAI 2026."

[[news]]
date = "2025-11"
content = "Started research internship at Tencent."

[[news]]
date = "2025-09"
content = "Started my PhD at Wuhan University."

[[news]]
date = "2025-06"
content = "Honored as Outstanding Master's Graduate of Zhejiang Province."

[[news]]
date = "2025-06"
content = "One paper accepted by IEEE TNNLS."

[[news]]
date = "2024-09"
content = "One paper accepted by IEEE ICDM 2024."

[[news]]
date = "2024-04"
content = "One paper accepted by IEEE TIFS."

[[news]]
date = "2024-03"
content = "One paper accepted by Information Sciences."
